version: '3.8'

services:
  nginx:
    restart: on-failure
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    networks:
      - my_network
    depends_on:
      - wordpress

  mariadb:
    restart: on-failure
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql/
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT_PASS: ${DB_ROOT_PASS}
        DB_NAME: ${DB_NAME}
    image: mariadb
    networks:
      - my_network

  wordpress:
    restart: on-failure
    container_name: wordpress
    volumes:
      - wp:/var/www/html
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - WP_USER=${WP_USER}
      - WP_PASS=${WP_PASS}
      - WP_ADMIN=${WP_ADMIN}
      - WP_URL=${WP_URL}
      - WP_E_A=${WP_E_A}
      - WP_E=${WP_E}
    image: wordpress
    networks:
      - my_network
    depends_on:
      - mariadb

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${LOGIN}/data/db
  wp:
    name: wp
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${LOGIN}/data/wp

networks:
  my_network:
    name: my_network
    driver: bridge
    external: "false"